version: "3.8"

services:
  app:
    build:
      context: ./app
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: hotel_db
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  loadbalancer:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./loadbalancer/nginx.conf:/etc/nginx/nginx.conf:ro # Fixed path for nginx.conf inside the loadbalancer folder
    depends_on:
      - app
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
